version: "3"
services:
  api:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "0.0.0.0:4000:4000"
    volumes:
      - .:/app
      - ./node_modules/:/app/node_modules
    command: node main.js

  db:
    image: postgres:alpine
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "htmlAdmin"
      POSTGRES_PASSWORD: "html"
      POSTGRES_DB: "html"
  
  redis:
    image: redis:5.0.4-alpine
    ports:
      - "0.0.0.0:6379:6379"
